language: node_js
node_js:
  - "6"
before_install:
  - stty columns 120
install:
  - npm install
script:
  - webpack --config config/webpack.prod.js
after_success:
  - surge --project ./dist --domain abhiesa1.surge.sh

